import {onAuthStateChanged,RecaptchaVerifier,linkWithPhoneNumber} from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import {auth} from "./firebase-config.js";
import {getBusinessContext,hydrateBusiness,workspaceError,saveBusinessProfile} from "./business-context.js";
const form=document.querySelector('[data-business-profile]'),button=form.querySelector('[type=submit]'),retry=document.querySelector('[data-profile-retry]'),status=document.querySelector('[data-profile-status]');
const fields={'business-name':'businessName','business-type':'businessType',industry:'industry',country:'country',phone:'phone',address:'address',about:'about'};
let context=null,currentUser=null,busy=false,confirmationResult=null,recaptcha=null,map=null,marker=null,currentPoint=null,verification=null;
const $=s=>document.querySelector(s);
function show(message,tone='error'){status.hidden=false;status.textContent=message;status.className='form-status '+tone;}
function completion(data){const values=Object.values(fields).map(key=>String(data[key]||'').trim());return Math.round(values.filter(Boolean).length/values.length*100);}
function renderLogo(url){const img=$('[data-business-logo-image]'),initial=$('[data-logo-preview] [data-business-initial]'),remove=$('[data-remove-logo]');if(url){img.onload=()=>{document.querySelectorAll('.workspace-avatar,.account-avatar,.profile-emblem').forEach(n=>{n.classList.add('has-logo');n.style.backgroundImage=`url("${url}")`;});};img.onerror=()=>show('The image was saved but could not be displayed. Check the uploads/business-logos folder permissions.');img.src=url;img.hidden=false;initial.hidden=true;remove.hidden=false;}else{img.removeAttribute('src');img.hidden=true;initial.hidden=false;remove.hidden=true;}document.querySelectorAll('.workspace-avatar,.account-avatar,.profile-emblem').forEach(n=>{n.classList.toggle('has-logo',!!url);n.style.backgroundImage=url?`url("${url}")`:'';});$('[data-logo-status]').textContent=url?'Image uploaded. You can replace it at any time.':'Your business initial is shown until you upload an image.';}
async function logoRequest(method,file){const token=await currentUser.getIdToken();const opts={method,headers:{Authorization:'Bearer '+token}};if(file){const fd=new FormData();fd.append('logo',file);opts.body=fd;}const res=await fetch('api/business-logo.php',opts);const d=await res.json();if(!res.ok||!d.ok)throw new Error(d.error||'Image update failed');return d;}
function updateSummary(data){$('[data-profile-progress]').textContent=completion(data)+'%';$('[data-verification-status]').textContent=data.profileComplete?'Information complete':'In progress';}
async function api(action,options={}){const token=await currentUser.getIdToken();const r=await fetch('api/workspace.php?action='+encodeURIComponent(action),{...options,headers:{...(options.headers||{}),Authorization:'Bearer '+token}});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'Request failed');return d;}
function renderVerification(v={}){
 verification=v;const items=[['[data-check-phone]',v.phoneVerified],['[data-check-identity]',v.identityVerified],['[data-check-location]',v.locationConfirmed],['[data-check-proof]',v.proofOfAddressUploaded]];
 items.forEach(([s,done])=>{const n=$(s);if(!n)return;n.classList.toggle('done',!!done);const icon=n.querySelector(':scope > span');if(icon)icon.textContent=done?'✓':'○';});
 const count=Number(v.completed||0),total=Number(v.total||4);$('[data-verification-title]').textContent=`Business verification — ${count} of ${total} complete`;$('[data-verification-badge]').textContent=`${count}/${total}`;$('[data-verification-badge]').classList.toggle('success',count===total);
 const identitySummary=$('[data-identity-summary]');if(identitySummary)identitySummary.textContent=v.identityVerified?'Identity verified ✓':v.identityStatus==='pending'?'ID + selfie submitted · awaiting review':v.identityStatus==='rejected'?'Verification needs attention · resubmit':'Upload your ID and take a live selfie.';
 $('[data-send-otp]').textContent=v.phoneVerified?'Phone verified ✓':'Verify phone';$('[data-send-otp]').disabled=!!v.phoneVerified;
 $('[data-location-status]').textContent=v.locationConfirmed?'Location confirmed ✓':'Location not confirmed';
 $('[data-proof-status]').textContent=v.proofOfAddressUploaded?`Uploaded: ${v.proofOfAddress?.originalName||'proof of address'}`:'Your document is stored privately and is not shown to customers.';
 if(v.location?.lat!=null&&v.location?.lng!=null){setMapPoint(Number(v.location.lat),Number(v.location.lng),false);}
}
function normalizePhone(raw){let s=String(raw||'').replace(/[\s()-]/g,'');if(/^0\d{9}$/.test(s))s='+27'+s.slice(1);if(/^27\d{9}$/.test(s))s='+'+s;return s;}
function initMap(){if(map||!window.L)return;map=L.map('businessMap').setView([-30.5595,22.9375],5);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);map.on('click',e=>setMapPoint(e.latlng.lat,e.latlng.lng,true));}
function setMapPoint(lat,lng,pan=true){initMap();currentPoint={lat,lng};if(!marker){marker=L.marker([lat,lng],{draggable:true}).addTo(map);marker.on('dragend',()=>{const p=marker.getLatLng();currentPoint={lat:p.lat,lng:p.lng};reverseAddress(p.lat,p.lng);});}else marker.setLatLng([lat,lng]);if(pan)map.setView([lat,lng],16);}
async function reverseAddress(lat,lng){try{const r=await fetch(`https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${encodeURIComponent(lat)}&lon=${encodeURIComponent(lng)}&addressdetails=1`,{headers:{Accept:'application/json'}});if(!r.ok)return;const d=await r.json();if(d.display_name)form.elements.address.value=d.display_name;}catch(e){console.warn('Reverse geocoding failed',e);}}
async function refreshVerification(){const d=await api('verification');renderVerification(d.verification||{});}
async function load(){if(!currentUser||busy)return;button.disabled=true;retry.hidden=true;show('Loading your saved details…','info');try{context=await getBusinessContext(currentUser,{refresh:true});const business=context.business||{};for(const [field,key] of Object.entries(fields)){const control=form.elements[field],value=business[key];if(value!=null){if(control.tagName==='SELECT'&&![...control.options].some(o=>o.value===value))control.add(new Option(value,value));control.value=value;}}hydrateBusiness(context,currentUser);updateSummary(business);renderLogo(business.logoUrl||'');initMap();await refreshVerification();status.hidden=!!context.business;if(!context.business)show('Finish your business details to create your workspace.','info');button.disabled=false;button.textContent='Save changes';}catch(error){context=null;show(workspaceError(error,'load your business profile'));retry.hidden=false;button.textContent='Save changes';}}
form.addEventListener('submit',async e=>{e.preventDefault();if(busy)return;if(!context||!currentUser){show('Your profile has not loaded yet. Select Retry loading before saving.');retry.hidden=false;return;}if(!form.reportValidity())return;const payload={};for(const [field,key] of Object.entries(fields))payload[key]=form.elements[field].value.trim();if(!payload.businessName||!payload.industry){show('Enter a business name and industry.');return;}payload.profileComplete=completion(payload)===100;payload.setupProgress=completion(payload);busy=true;button.disabled=true;button.textContent='Saving…';show('Saving your business profile…','info');try{const saved=await saveBusinessProfile(currentUser,payload);context.business=saved.business||{...context.business,...payload};hydrateBusiness(context,currentUser);updateSummary(context.business);await refreshVerification();show(payload.profileComplete?'Your business information is complete. Finish the verification checks shown on the right.':'Your business profile has been saved. Complete all fields before adding products.','success');}catch(error){show(workspaceError(error,'save your business profile'));}finally{busy=false;button.disabled=false;button.textContent='Save changes';}});
$('[data-send-otp]').addEventListener('click',async()=>{const phone=normalizePhone(form.elements.phone.value);if(!/^\+\d{10,15}$/.test(phone)){show('Enter a valid mobile number, for example +27 60 123 4567.');return;}try{$('[data-send-otp]').disabled=true;$('[data-send-otp]').textContent='Sending…';if(recaptcha){try{recaptcha.clear();}catch(_){}recaptcha=null;document.getElementById('phone-recaptcha').replaceChildren();}recaptcha=new RecaptchaVerifier(auth,'phone-recaptcha',{size:'invisible'});confirmationResult=await linkWithPhoneNumber(currentUser,phone,recaptcha);$('[data-otp-panel]').hidden=false;$('[data-otp-status]').textContent='Code sent to '+phone;show('Verification code sent.','success');}catch(e){console.error(e);show(e.code==='auth/operation-not-allowed'?'SMS verification is not enabled for this phone region yet. Enable South Africa in Firebase Authentication → Settings → SMS region policy, then try again.':e.code==='auth/credential-already-in-use'?'That phone number is already linked to another account.':'Could not send the verification code. Check the number and try again.');$('[data-send-otp]').disabled=false;$('[data-send-otp]').textContent='Verify phone';}});
$('[data-resend-otp]').addEventListener('click',()=>{ $('[data-send-otp]').disabled=false; $('[data-send-otp]').click(); });
$('[data-confirm-otp]').addEventListener('click',async()=>{const code=$('[data-otp-code]').value.trim();if(!/^\d{6}$/.test(code)){show('Enter the 6-digit verification code.');return;}try{$('[data-confirm-otp]').disabled=true;await confirmationResult.confirm(code);await currentUser.reload();form.elements.phone.value=normalizePhone(form.elements.phone.value);const payload={...context.business,phone:form.elements.phone.value};payload.profileComplete=completion(payload)===100;payload.setupProgress=completion(payload);const saved=await saveBusinessProfile(currentUser,payload);context.business=saved.business;await refreshVerification();$('[data-otp-panel]').hidden=true;show('Business phone verified successfully.','success');}catch(e){console.error(e);show('The verification code is invalid or expired. Please try again.');}finally{$('[data-confirm-otp]').disabled=false;}});
$('[data-use-location]').addEventListener('click',()=>{if(!navigator.geolocation){show('Location is not supported by this browser.');return;}const b=$('[data-use-location]');b.disabled=true;b.textContent='Finding location…';navigator.geolocation.getCurrentPosition(async p=>{setMapPoint(p.coords.latitude,p.coords.longitude,true);await reverseAddress(p.coords.latitude,p.coords.longitude);$('[data-location-status]').textContent=`Location found · accuracy ±${Math.round(p.coords.accuracy)}m. Move the pin if needed.`;b.disabled=false;b.textContent='Use my current location';},()=>{show('Teyza could not access your location. Allow location permission or choose the address on the map.');b.disabled=false;b.textContent='Use my current location';},{enableHighAccuracy:true,timeout:15000,maximumAge:0});});
$('[data-confirm-location]').addEventListener('click',async()=>{if(!currentPoint){show('Use your current location or choose a point on the map first.');return;}const address=form.elements.address.value.trim();if(!address){show('Enter or select the business address before confirming the location.');return;}try{const d=await api('verification',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'location',lat:currentPoint.lat,lng:currentPoint.lng,address})});renderVerification(d.verification);show('Business location confirmed.','success');}catch(e){show(e.message);}});
$('[data-upload-proof]').addEventListener('click',async()=>{const file=$('[data-proof-file]').files[0];if(!file){show('Choose a proof of address document first.');return;}const b=$('[data-upload-proof]');try{b.disabled=true;b.textContent='Uploading…';const token=await currentUser.getIdToken();const fd=new FormData();fd.append('proof',file);const r=await fetch('api/verification-upload.php',{method:'POST',headers:{Authorization:'Bearer '+token},body:fd});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'Upload failed');await refreshVerification();show('Proof of address uploaded securely.','success');}catch(e){show(e.message);}finally{b.disabled=false;b.textContent='Upload proof';}});
form.elements.phone.addEventListener('input',()=>{if(verification?.phoneVerified){verification={...verification,phoneVerified:false,completed:Math.max(0,Number(verification.completed||0)-1)};renderVerification(verification);}});
$('[data-upload-logo]').addEventListener('click',async()=>{const file=$('[data-logo-file]').files[0];if(!file){show('Choose a JPG or PNG image first.');return;}const b=$('[data-upload-logo]');try{b.disabled=true;b.textContent='Uploading…';const d=await logoRequest('POST',file);context.business.logoUrl=d.logoUrl;renderLogo(d.logoUrl);show('Seller photo / business logo updated.','success');}catch(e){show(e.message);}finally{b.disabled=false;b.textContent='Upload image';}});
$('[data-remove-logo]').addEventListener('click',async()=>{try{const d=await logoRequest('DELETE');delete context.business.logoUrl;renderLogo(d.logoUrl);show('Business image removed.','success');}catch(e){show(e.message);}});
let identityStream=null,selfieBlob=null,identityStep=1;const identityModal=$('[data-identity-modal]'),identityFile=$('[data-identity-document]');
function identityStatus(message,type='error'){const s=$('[data-identity-status]');s.hidden=false;s.textContent=message;s.className='form-status '+type;}
function setIdentityStep(step){identityStep=step;document.querySelectorAll('[data-identity-step]').forEach(p=>{const active=Number(p.dataset.identityStep)===step;p.hidden=!active;p.classList.toggle('active',active)});document.querySelectorAll('[data-identity-progress]').forEach(p=>{const n=Number(p.dataset.identityProgress);p.classList.toggle('active',n===step);p.classList.toggle('done',n<step)});if(step===3){$('[data-review-document]').textContent=identityFile.files[0]?.name||'Not selected';$('[data-review-document-status]').textContent=identityFile.files[0]?'Ready ✓':'Required';$('[data-review-selfie]').textContent=selfieBlob?'Selfie captured':'Not captured';$('[data-review-selfie-status]').textContent=selfieBlob?'Ready ✓':'Required';}}
function stopIdentityCamera(){if(identityStream){identityStream.getTracks().forEach(t=>t.stop());identityStream=null;}}
$('[data-open-identity]').addEventListener('click',()=>{setIdentityStep(1);identityModal.classList.add('show');identityModal.setAttribute('aria-hidden','false')});
function closeIdentity(){stopIdentityCamera();identityModal.classList.remove('show');identityModal.setAttribute('aria-hidden','true');}$('[data-close-identity]').addEventListener('click',closeIdentity);
identityFile.addEventListener('change',()=>{$('[data-identity-file-name]').textContent=identityFile.files[0]?.name||'Tap to select a file · Maximum 8 MB'});
document.querySelectorAll('[data-identity-next]').forEach(b=>b.addEventListener('click',()=>{const next=Number(b.dataset.identityNext);if(next===2&&!identityFile.files[0]){identityStatus('Choose your identity document before continuing.');return;}if(next===3&&!selfieBlob){identityStatus('Capture your live selfie before continuing.');return;}setIdentityStep(next)}));
document.querySelectorAll('[data-identity-back]').forEach(b=>b.addEventListener('click',()=>setIdentityStep(Number(b.dataset.identityBack))));
$('[data-start-camera]').addEventListener('click',async()=>{try{identityStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:720},height:{ideal:720}},audio:false});const v=$('[data-identity-video]');v.srcObject=identityStream;v.hidden=false;$('[data-camera-placeholder]').hidden=true;$('[data-capture-selfie]').disabled=false;$('[data-start-camera]').textContent='Camera active';$('[data-start-camera]').disabled=true;}catch(e){identityStatus('Camera access is required. Allow camera permission in your browser and try again.')}});
$('[data-capture-selfie]').addEventListener('click',()=>{const v=$('[data-identity-video]'),canvas=$('[data-identity-canvas]');canvas.width=v.videoWidth||640;canvas.height=v.videoHeight||640;canvas.getContext('2d').drawImage(v,0,0,canvas.width,canvas.height);canvas.toBlob(blob=>{selfieBlob=blob;const img=$('[data-identity-selfie-preview]');img.src=URL.createObjectURL(blob);img.hidden=false;v.hidden=true;$('[data-retake-selfie]').hidden=false;$('[data-capture-selfie]').hidden=true;stopIdentityCamera();},'image/jpeg',.86)});
$('[data-retake-selfie]').addEventListener('click',()=>{selfieBlob=null;$('[data-identity-selfie-preview]').hidden=true;$('[data-camera-placeholder]').hidden=false;$('[data-retake-selfie]').hidden=true;$('[data-capture-selfie]').hidden=false;$('[data-capture-selfie]').disabled=true;$('[data-start-camera]').disabled=false;$('[data-start-camera]').textContent='Start camera'});
$('[data-submit-identity]').addEventListener('click',async()=>{const doc=identityFile.files[0],consent=$('[data-identity-consent]').checked,b=$('[data-submit-identity]');if(!doc||!selfieBlob){identityStatus('Your ID document and live selfie are both required.');return;}if(!consent){identityStatus('Please confirm consent before submitting.');return;}try{b.disabled=true;b.textContent='Submitting securely…';const token=await currentUser.getIdToken();const fd=new FormData();fd.append('type','identity');fd.append('document',doc);fd.append('selfie',selfieBlob,'live-selfie.jpg');fd.append('consent','yes');const res=await fetch('api/verification-upload.php',{method:'POST',headers:{Authorization:'Bearer '+token},body:fd});const d=await res.json();if(!res.ok||!d.ok)throw new Error(d.error||'Identity submission failed');await refreshVerification();identityStatus('Submitted successfully. Your identity is now awaiting Teyza review.','success');b.textContent='Submitted ✓';setTimeout(closeIdentity,1800);}catch(e){identityStatus(e.message);}finally{if(b.textContent!=='Submitted ✓'){b.disabled=false;b.textContent='Submit for verification';}}});
retry.addEventListener('click',load);onAuthStateChanged(auth,user=>{currentUser=user;if(user)load();else{context=null;button.disabled=true;}});
