import {GoogleAuthProvider,createUserWithEmailAndPassword,getAdditionalUserInfo,signInWithEmailAndPassword,signInWithPopup,updateProfile} from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import {auth} from "./firebase-config.js";
const provider=new GoogleAuthProvider();provider.setCustomParameters({prompt:'select_account'});
if(!document.getElementById('teyzaAuthCss'))document.head.insertAdjacentHTML('beforeend',`<style id="teyzaAuthCss">.tz-auth{position:fixed;inset:0;z-index:9999;background:rgba(4,11,28,.68);backdrop-filter:blur(12px);display:none;align-items:center;justify-content:center;padding:20px}.tz-auth.open{display:flex}.tz-card{width:min(480px,100%);max-height:94vh;overflow:auto;background:#fff;border-radius:26px;padding:30px;box-shadow:0 35px 100px rgba(7,20,47,.35);position:relative}.tz-close{position:absolute;right:18px;top:18px;border:0;background:#f3f5f9;width:38px;height:38px;border-radius:50%;font-size:20px;cursor:pointer}.tz-brand{font:800 18px Inter;color:#07142f;letter-spacing:.08em}.tz-brand b{display:inline-grid;place-items:center;width:34px;height:34px;margin-right:9px;border-radius:10px;color:#fff;background:linear-gradient(135deg,#1ed7dd,#168cff,#6739e6,#e633ae,#ff9c28)}.tz-card h2{font:800 30px Inter;margin:25px 0 8px;color:#07142f}.tz-sub{color:#69738a;margin:0 0 22px}.tz-google,.tz-submit{width:100%;height:50px;border-radius:13px;font-weight:800;cursor:pointer}.tz-google{background:#fff;border:1px solid #dfe3ec}.tz-submit{border:0;color:#fff;background:linear-gradient(110deg,#168cff,#6739e6,#e633ae)}.tz-or{display:flex;align-items:center;gap:10px;color:#9098a8;font-size:12px;margin:18px 0}.tz-or:before,.tz-or:after{content:'';height:1px;background:#e5e8ef;flex:1}.tz-field{display:block;font-size:12px;font-weight:800;color:#39445b;margin:12px 0}.tz-field input{display:block;width:100%;height:48px;border:1px solid #dfe3ec;border-radius:12px;padding:0 13px;margin-top:6px;font:500 14px Inter}.tz-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.tz-switch{text-align:center;color:#69738a;font-size:13px;margin:18px 0 0}.tz-switch button{border:0;background:none;color:#5b36d4;font-weight:800;cursor:pointer}.tz-status{padding:10px 12px;border-radius:10px;background:#fff0f0;color:#a52727;font-size:13px;margin:12px 0}.tz-status.ok{background:#ecfbf5;color:#087653}@media(max-width:520px){.tz-card{padding:25px 20px}.tz-grid{grid-template-columns:1fr}}</style>`);
const loginMarkup=`<div class="tz-auth" id="tzLogin" aria-hidden="true"><div class="tz-card" role="dialog" aria-modal="true" aria-label="Log in to Teyza"><button class="tz-close" type="button" data-close aria-label="Close">×</button><div class="tz-brand"><b>T</b>TEYZA</div><h2>Welcome back.</h2><p class="tz-sub">Log in to continue to your selling workspace.</p><button class="tz-google" type="button" id="tzGoogleLogin">G &nbsp; Continue with Google</button><div class="tz-or">OR CONTINUE WITH EMAIL</div><form id="tzLoginForm"><label class="tz-field">Email<input type="email" name="email" autocomplete="email" required></label><label class="tz-field">Password<input type="password" name="password" autocomplete="current-password" required></label><div class="tz-status" data-status role="status" hidden></div><button class="tz-submit" type="submit">Log in to Teyza</button></form><p class="tz-switch">New to Teyza? <button type="button" data-open-register>Create account</button></p></div></div>`;
const registerMarkup=`<div class="tz-auth" id="tzRegister" aria-hidden="true"><div class="tz-card" role="dialog" aria-modal="true" aria-label="Create a Teyza account"><button class="tz-close" type="button" data-close aria-label="Close">×</button><div class="tz-brand"><b>T</b>TEYZA</div><h2>Start selling.</h2><p class="tz-sub">Create your free Teyza workspace in less than a minute.</p><button class="tz-google" type="button" id="tzGoogleRegister">G &nbsp; Continue with Google</button><div class="tz-or">OR CREATE WITH EMAIL</div><form id="tzRegisterForm"><div class="tz-grid"><label class="tz-field">First name<input name="firstName" autocomplete="given-name" required></label><label class="tz-field">Last name<input name="lastName" autocomplete="family-name" required></label></div><label class="tz-field">Email<input type="email" name="email" autocomplete="email" required></label><label class="tz-field">Password<input type="password" name="password" autocomplete="new-password" minlength="6" required></label><label class="tz-field">Store or business name <span style="font-weight:500;color:#8b93a3">(optional)</span><input name="businessName" autocomplete="organization" placeholder="e.g. Gatcheni Stores"></label><div class="tz-status" data-status role="status" hidden></div><button class="tz-submit" type="submit">Create my Teyza account</button></form><p class="tz-switch">Already have an account? <button type="button" data-open-login>Log in</button></p></div></div>`;
if(!document.getElementById('loginModal')&&!document.getElementById('tzLogin'))document.body.insertAdjacentHTML('beforeend',loginMarkup);if(!document.getElementById('tzRegister'))document.body.insertAdjacentHTML('beforeend',registerMarkup);
const login=document.getElementById('loginModal')||document.getElementById('tzLogin'),register=document.getElementById('tzRegister');
function open(m){document.querySelectorAll('.tz-auth,.auth-overlay').forEach(x=>{x.classList.remove('open');x.setAttribute('aria-hidden','true')});m?.classList.add('open');m?.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');m?.querySelector('input')?.focus()}function close(m){m?.classList.remove('open');m?.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open')}function status(f,msg,ok=false){const n=f?.querySelector('[data-status],[data-auth-status],#authStatus');if(n){n.hidden=false;n.textContent=msg;n.classList.toggle('ok',ok);n.classList.toggle('success',ok)}}
async function bootstrap(user,details={}){const token=await user.getIdToken();const r=await fetch('api/workspace.php?action=bootstrap',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(details)});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.error||'Unable to prepare your Teyza workspace. Please retry.');return d}
const allowedDestinations=new Set(['dashboard.html','products.html','orders.html','customers.html','business-profile.html','seller-onboarding.html','shop-settings.html','delivery-settings.html','payments.html','sales-channels.html','network.html','store.html']);
function loginDestination(){const target=new URLSearchParams(location.search).get('redirect')||'dashboard.html';return allowedDestinations.has(target.split(/[?#]/)[0])&&!target.includes('\\')&&!target.includes('/')?target:'dashboard.html'}
const go=()=>location.assign(loginDestination());const goNewSeller=()=>location.assign('dashboard.html?onboarding=1');
document.addEventListener('click',e=>{const r=e.target.closest('a[href="register.html"],[data-open-register]');if(r){e.preventDefault();open(register);return}const l=e.target.closest('a[href="login.html"],[data-open-login]');if(l){e.preventDefault();open(login);return}const c=e.target.closest('[data-close],[data-close-login]');if(c){close(c.closest('.tz-auth,.auth-overlay'));return}if(e.target.classList.contains('tz-auth')||e.target.classList.contains('auth-overlay'))close(e.target)});
const lf=document.getElementById('tzLoginForm')||document.getElementById('premiumLogin');lf?.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(lf),b=lf.querySelector('[type=submit]');b.disabled=true;try{const email=String(fd.get('email')||document.getElementById('loginEmail')?.value||'').trim(),pass=String(fd.get('password')||document.getElementById('loginPassword')?.value||'');const c=await signInWithEmailAndPassword(auth,email,pass);await bootstrap(c.user);status(lf,'Welcome back. Opening Teyza…',true);setTimeout(go,300)}catch(x){status(lf,x.code==='auth/invalid-credential'?'Incorrect email or password.':x.message||'Unable to log in.');b.disabled=false}});
const rf=document.getElementById('tzRegisterForm');rf.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(rf),b=rf.querySelector('[type=submit]'),email=String(fd.get('email')).trim(),full=`${fd.get('firstName')} ${fd.get('lastName')}`.trim();b.disabled=true;try{let user=auth.currentUser;const pendingUid=sessionStorage.getItem('teyzaPendingEnrollment');if(!user||user.uid!==pendingUid||user.email?.toLowerCase()!==email.toLowerCase()){user=(await createUserWithEmailAndPassword(auth,email,String(fd.get('password')))).user;sessionStorage.setItem('teyzaPendingEnrollment',user.uid)}if(user.displayName!==full)await updateProfile(user,{displayName:full});await bootstrap(user,{firstName:String(fd.get('firstName')).trim(),businessName:String(fd.get('businessName')).trim()});sessionStorage.removeItem('teyzaPendingEnrollment');status(rf,'Your Teyza account is ready. Let’s set up your business.',true);setTimeout(goNewSeller,300)}catch(x){status(rf,x.code==='auth/email-already-in-use'?'This email already has a Teyza account. Log in instead.':x.message||'Unable to create your account.');b.disabled=false}});
async function google(mode,button){if(button.disabled)return;const m=mode==='register'?register:login,f=m.querySelector('form');button.disabled=true;try{const c=await signInWithPopup(auth,provider),isNew=getAdditionalUserInfo(c)?.isNewUser===true;await bootstrap(c.user);status(f,isNew?'Account created. Let’s set up your business.':'Connected. Opening Teyza…',true);setTimeout(isNew?goNewSeller:go,300)}catch(x){status(f,x.code==='auth/popup-closed-by-user'?'Google sign-in was closed.':x.message||'Google sign-in failed.');button.disabled=false}}document.getElementById('tzGoogleLogin')?.addEventListener('click',e=>google('login',e.currentTarget));document.getElementById('googleLogin')?.addEventListener('click',e=>google('login',e.currentTarget));document.getElementById('tzGoogleRegister')?.addEventListener('click',e=>google('register',e.currentTarget));
const requested=new URLSearchParams(location.search).get('auth');if(requested==='login')open(login);if(requested==='register')open(register);

document.addEventListener('keydown',e=>{if(e.key==='Escape'){const openModal=document.querySelector('.tz-auth.open,.auth-overlay.open');if(openModal)close(openModal)}});
