import {onAuthStateChanged} from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";import {auth} from "./firebase-config.js";import {getWorkspaceSection,saveWorkspaceSection} from "./business-context.js";
const modal=document.querySelector("#teyzaOnboarding"),msg=document.querySelector("[data-ob-message]");let user=null,state=null,pay="eft";
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
async function api(action,options={}){const token=await user.getIdToken();const r=await fetch("api/workspace.php?action="+action,{...options,headers:{...(options.headers||{}),Authorization:"Bearer "+token}});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"Request failed");return d}
function yes(el,v,label){el.textContent=(v?"✓ ":"○ ")+label;el.classList.toggle("done",!!v)}
function stage(n){qa("[data-ob-step]").forEach(x=>x.hidden=Number(x.dataset.obStep)!==n);qa("[data-ob-tab]").forEach(x=>{const v=Number(x.dataset.obTab);x.classList.toggle("active",v===n);x.classList.toggle("done",v<n);x.disabled=v>n});q("[data-ob-count]").textContent="Step "+n+" of 3";msg.hidden=true}
async function load(){state=await api("seller-readiness");if(state.productReady){modal.hidden=true;document.body.classList.remove("ob2-open");history.replaceState({},document.title,"dashboard.html");return}modal.hidden=false;document.body.classList.add("ob2-open");const v=state.businessVerification||{};yes(q("[data-ob-business-info]"),state.missingBusinessFields?.length===0,"Business information");yes(q("[data-ob-phone]"),v.phoneVerified,"Phone verification");yes(q("[data-ob-identity]"),v.identitySubmitted||v.identityVerified,"ID + live selfie");yes(q("[data-ob-location]"),v.locationConfirmed,"Location confirmed");yes(q("[data-ob-proof]"),v.proofOfAddressUploaded,"Proof of address");if(!state.businessComplete)return stage(1);if(!state.deliveryComplete){const d=(await getWorkspaceSection(user,"delivery").catch(()=>({data:{}}))).data||{};q("[data-ob-delivery-method]").value=d.fulfilmentMode||"courier";q("[data-ob-provider]").value=d.courierPreference||"";q("[data-ob-address]").value=d.pickupAddress||"";q("[data-ob-fee]").value=d.baseDeliveryFee||0;return stage(2)}const [b,p,o]=await Promise.all(["banking","payfast","paymentPreferences"].map(s=>getWorkspaceSection(user,s).catch(()=>({data:{}}))));if(b.data?.bankName){q("[data-ob-bank]").value=b.data.bankName||"";q("[data-ob-holder]").value=b.data.accountHolder||"";q("[data-ob-branch]").value=b.data.branchCode||""}if(p.data?.merchantId)q("[data-ob-merchant]").value=p.data.merchantId;if(o.data?.otherGateway){q("[data-ob-gateway]").value=o.data.otherGateway;q("[data-ob-reference]").value=o.data.otherReference||""}stage(3)}
q("[data-ob-save-delivery]")?.addEventListener("click",async e=>{const b=e.currentTarget;b.disabled=true;b.textContent="Saving…";try{await saveWorkspaceSection(user,"delivery",{fulfilmentMode:q("[data-ob-delivery-method]").value,courierPreference:q("[data-ob-provider]").value.trim(),pickupAddress:q("[data-ob-address]").value.trim(),baseDeliveryFee:Number(q("[data-ob-fee]").value||0),trackingEnabled:true});await api("seller-readiness",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({deliveryComplete:true})});await load()}catch(x){msg.hidden=false;msg.textContent=x.message}finally{b.disabled=false;b.textContent="Save & continue →"}});
qa("[data-ob-pay]").forEach(b=>b.addEventListener("click",()=>{pay=b.dataset.obPay;qa("[data-ob-pay]").forEach(x=>x.classList.toggle("active",x===b));qa("[data-ob-pay-fields]").forEach(x=>x.hidden=x.dataset.obPayFields!==pay)}));
q("[data-ob-save-payment]")?.addEventListener("click",async e=>{const b=e.currentTarget;b.disabled=true;b.textContent="Saving…";try{if(pay==="eft"){const bank=q("[data-ob-bank]").value.trim(),holder=q("[data-ob-holder]").value.trim(),account=q("[data-ob-account]").value.trim();if(!bank||!holder||!account)throw new Error("Complete the bank, account holder and account number.");await saveWorkspaceSection(user,"banking",{bankName:bank,accountHolder:holder,accountNumber:account,accountNumberLast4:account.slice(-4),branchCode:q("[data-ob-branch]").value.trim(),accountType:"Business"})}else if(pay==="payfast"){const id=q("[data-ob-merchant]").value.trim(),key=q("[data-ob-key]").value;if(!id||!key)throw new Error("Enter your PayFast Merchant ID and Merchant Key.");await saveWorkspaceSection(user,"payfast",{merchantId:id,merchantKey:key,connected:true})}else{const gateway=q("[data-ob-gateway]").value.trim();if(!gateway)throw new Error("Enter your payment gateway.");await saveWorkspaceSection(user,"paymentPreferences",{otherGateway:gateway,otherReference:q("[data-ob-reference]").value.trim()})}await api("seller-readiness",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({paymentComplete:true,sellerSetupComplete:true})});await load()}catch(x){msg.hidden=false;msg.textContent=x.message}finally{b.disabled=false;b.textContent="Finish setup →"}});
onAuthStateChanged(auth,async u=>{if(!u)return;user=u;try{await load()}catch(e){modal.hidden=false;document.body.classList.add("ob2-open");msg.hidden=false;msg.textContent=e.message}});
