import {onAuthStateChanged} from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import {auth} from "./firebase-config.js";
import {getBusinessContext,getWorkspaceOrders,createWorkspaceOrder,workspaceError} from "./business-context.js";
const form=document.querySelector("[data-order-form]"), statusNode=document.querySelector("[data-order-status]"), tableBody=document.querySelector("[data-orders-table-body]");
const productSelect=form?.elements["productId"];const cols={new:document.querySelector('[data-order-column="new"]'),processing:document.querySelector('[data-order-column="processing"]'),shipping:document.querySelector('[data-order-column="shipping"]')};
const money=new Intl.NumberFormat("en-ZA",{style:"currency",currency:"ZAR"});let user=null;
function status(m,t="error"){if(statusNode){statusNode.hidden=false;statusNode.textContent=m;statusNode.className="form-status "+t}}
function norm(v){v=String(v||"new").toLowerCase();return ["processing","shipping","completed"].includes(v)?v:"new"}
function render(orders,products){if(productSelect)productSelect.innerHTML='<option value="">Select product</option>'+products.map(p=>'<option value="'+p.id+'">'+p.name+' ('+money.format(Number(p.price||0))+')</option>').join("");
 if(tableBody)tableBody.innerHTML=orders.length?orders.map(o=>'<tr><td>'+o.orderNumber+'</td><td>'+String(o.customerName||o.customerId||"-")+'</td><td>'+norm(o.orderStatus)+'</td><td>'+String(o.paymentStatus||"pending").toUpperCase()+'</td><td>'+money.format(Number(o.total||0))+'</td></tr>').join(""):'<tr><td colspan="5">No orders yet.</td></tr>';
 for(const key of ["new","processing","shipping"]){const list=orders.filter(o=>norm(o.orderStatus)===key).slice(0,5);if(cols[key])cols[key].innerHTML=list.length?list.map(o=>'<article><strong>'+o.orderNumber+'</strong><span>'+money.format(Number(o.total||0))+' · '+String(o.paymentStatus||"pending").toUpperCase()+'</span></article>').join(""):'<article><strong>No '+key+' orders</strong><span>Orders will appear here.</span></article>'}}
async function load(){const d=await getWorkspaceOrders(user);render(d.orders||[],d.products||[])}
form?.addEventListener("submit",async e=>{e.preventDefault();const b=form.querySelector('[type="submit"]');const fd=new FormData(form);b.disabled=true;b.textContent="Creating…";try{await createWorkspaceOrder(user,Object.fromEntries(fd.entries()));status("Order created successfully.","success");form.reset();if(form.elements.quantity)form.elements.quantity.value=1;await load()}catch(err){status(workspaceError(err,"create order"))}finally{b.disabled=false;b.textContent="Create order"}});
onAuthStateChanged(auth,async u=>{if(!u)return;user=u;try{const ctx=await getBusinessContext(u);document.querySelectorAll("[data-business-id]").forEach(n=>n.textContent=ctx.businessId||"");await load()}catch(e){status(workspaceError(e,"load orders"))}});
