import {onAuthStateChanged} from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import {auth} from "./firebase-config.js";
import {getBusinessContext,getWorkspaceSummary,workspaceError} from "./business-context.js";
const form=document.querySelector('[data-product-form]'),statusNode=document.querySelector('[data-product-status]'),tableBody=document.querySelector('[data-products-table-body]'),businessIdNode=document.querySelector('[data-business-id]');
const money=new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR'});let currentUser=null;
function showStatus(m,t='error'){if(statusNode){statusNode.hidden=false;statusNode.textContent=m;statusNode.className='form-status '+t}}
function safe(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function render(products=[]){if(!tableBody)return;window.products=products;tableBody.innerHTML=products.length?products.map(p=>`<tr><td><strong>${safe(p.name)}</strong>${p.images?.[0]?`<br><img src="${safe(p.images[0])}" alt="" style="width:48px;height:48px;object-fit:cover;border-radius:8px;margin-top:7px">`:''}</td><td>${safe(p.sku||'-')}</td><td>${money.format(Number(p.price||0))}</td><td>${money.format(Number(p.costPrice||0))}</td><td>${Number(p.stock||0)}</td><td><span class="muted">Teyza</span></td><td><span class="status-pill">Active</span></td><td>—</td></tr>`).join(''):'<tr><td colspan="8">No products yet. Add your first product above.</td></tr>'}
async function refresh(){const s=await getWorkspaceSummary(currentUser);render(s.products||[])}
const urlInput=form?.querySelector('input[name="imageUrl"]');if(urlInput){const label=urlInput.closest('label');if(label){label.innerHTML='Product images <small style="font-weight:400;color:#8b95a3">JPG, PNG or WebP · max 5MB each</small><input type="file" name="images" accept="image/jpeg,image/png,image/webp" multiple>';}}
if(form)form.addEventListener('submit',async e=>{e.preventDefault();if(!currentUser)return;const b=form.querySelector('[type=submit]'),fd=new FormData(form);if(!String(fd.get('name')||'').trim()){showStatus('Add a product name first.');return}b.disabled=true;b.textContent='Uploading & saving…';try{const token=await currentUser.getIdToken();if(fd.has('description'))fd.set('desc',String(fd.get('description')||''));const r=await fetch('upload_product.php',{method:'POST',headers:{Authorization:`Bearer ${token}`},body:fd});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'Unable to save product.');showStatus('Product saved to Teyza successfully.','success');form.reset();await refresh()}catch(x){showStatus(workspaceError(x,'save your product'))}finally{b.disabled=false;b.textContent='Add Product'}});
onAuthStateChanged(auth,user=>{if(!user){location.href='index.html?auth=login';return}currentUser=user;getBusinessContext(user).then(c=>{if(businessIdNode)businessIdNode.textContent=c.businessId;return refresh()}).catch(e=>showStatus(workspaceError(e)))});
