<?php
declare(strict_types=1);
header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');
const FIREBASE_API_KEY='AIzaSyC0dFsNcfwuYUbdCN6K2xrG3Ycx6tPvl_U';
function out(int $s,array $d):never{http_response_code($s);echo json_encode($d,JSON_UNESCAPED_SLASHES);exit;}
function user():array{$h=$_SERVER['HTTP_AUTHORIZATION']??'';if(!preg_match('/^Bearer\s+(.+)$/i',$h,$m))out(401,['ok'=>false,'error'=>'Authentication required']);$ch=curl_init('https://identitytoolkit.googleapis.com/v1/accounts:lookup?key='.rawurlencode(FIREBASE_API_KEY));curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_RETURNTRANSFER=>true,CURLOPT_HTTPHEADER=>['Content-Type: application/json'],CURLOPT_POSTFIELDS=>json_encode(['idToken'=>trim($m[1])]),CURLOPT_TIMEOUT=>12]);$raw=curl_exec($ch);$code=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);$j=json_decode((string)$raw,true);if($code!==200||empty($j['users'][0]['localId']))out(401,['ok'=>false,'error'=>'Your session is no longer valid']);return $j['users'][0];}
$u=user();$uid=preg_replace('/[^A-Za-z0-9_-]/','',$u['localId']);$dataDir=dirname(__DIR__).'/../private_html/teyza-data';$path=$dataDir.'/'.$uid.'.json';$w=is_file($path)?json_decode((string)file_get_contents($path),true):null;if(!is_array($w))out(404,['ok'=>false,'error'=>'Workspace not found']);
$publicDir=dirname(__DIR__).'/uploads/business-logos';if(!is_dir($publicDir)&&!mkdir($publicDir,0755,true)&&!is_dir($publicDir))out(500,['ok'=>false,'error'=>'Logo storage unavailable']);if(!is_writable($publicDir))out(500,['ok'=>false,'error'=>'Business logo folder is not writable by PHP']);
if($_SERVER['REQUEST_METHOD']==='DELETE'){foreach(glob($publicDir.'/'.$uid.'.*')?:[] as $old)@unlink($old);unset($w['business']['logoUrl']);file_put_contents($path,json_encode($w,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES),LOCK_EX);out(200,['ok'=>true,'logoUrl'=>null]);}
if($_SERVER['REQUEST_METHOD']!=='POST')out(405,['ok'=>false,'error'=>'Method not allowed']);
if(empty($_FILES['logo'])||$_FILES['logo']['error']!==UPLOAD_ERR_OK)out(422,['ok'=>false,'error'=>'Choose a JPG or PNG image']);
$f=$_FILES['logo'];if((int)$f['size']>5*1024*1024)out(413,['ok'=>false,'error'=>'Image must be 5 MB or smaller']);$mime=(new finfo(FILEINFO_MIME_TYPE))->file($f['tmp_name']);$ext=['image/jpeg'=>'jpg','image/png'=>'png'][$mime]??null;if(!$ext)out(415,['ok'=>false,'error'=>'Only JPG and PNG images are accepted']);
foreach(glob($publicDir.'/'.$uid.'.*')?:[] as $old)@unlink($old);$name=$uid.'.'.$ext;if(!move_uploaded_file($f['tmp_name'],$publicDir.'/'.$name))out(500,['ok'=>false,'error'=>'Could not store image']);$url='/uploads/business-logos/'.$name.'?v='.time();$w['business']['logoUrl']=$url;$w['business']['updatedAt']=gmdate('c');file_put_contents($path,json_encode($w,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES),LOCK_EX);out(200,['ok'=>true,'logoUrl'=>$url]);
